package com.ylcnfrht.blockchain.application.exceptions;

/**
 * Enum for application error codes.
 * Provides centralized error code management and type safety.
 */
public enum ErrorCode {
    
    // Wallet related errors
    WALLET_NOT_FOUND("WALLET_NOT_FOUND"),
    WALLET_CREATION_FAILED("WALLET_CREATION_FAILED"),
    WALLET_UPDATE_FAILED("WALLET_UPDATE_FAILED"),
    WALLET_DELETION_FAILED("WALLET_DELETION_FAILED"),
    WALLET_DEACTIVATION_FAILED("WALLET_DEACTIVATION_FAILED"),
    ADDRESS_ALREADY_EXISTS("ADDRESS_ALREADY_EXISTS"),
    BALANCE_CALCULATION_FAILED("BALANCE_CALCULATION_FAILED"),
    BALANCE_CHECK_FAILED("BALANCE_CHECK_FAILED"),
    BALANCE_UPDATE_FAILED("BALANCE_UPDATE_FAILED"),
    GET_ALL_WALLETS_FAILED("GET_ALL_WALLETS_FAILED"),
    GET_WALLET_BY_ID_FAILED("GET_WALLET_BY_ID_FAILED"),
    GET_WALLET_BY_ADDRESS_FAILED("GET_WALLET_BY_ADDRESS_FAILED"),
    TRANSACTION_HISTORY_FAILED("TRANSACTION_HISTORY_FAILED"),
    
    // Transaction related errors
    TRANSACTION_NOT_FOUND("TRANSACTION_NOT_FOUND"),
    TRANSACTION_CREATION_FAILED("TRANSACTION_CREATION_FAILED"),
    TRANSACTION_UPDATE_FAILED("TRANSACTION_UPDATE_FAILED"),
    TRANSACTION_DELETION_FAILED("TRANSACTION_DELETION_FAILED"),
    INVALID_TRANSACTION("INVALID_TRANSACTION"),
    INSUFFICIENT_BALANCE("INSUFFICIENT_BALANCE"),
    GET_ALL_TRANSACTIONS_FAILED("GET_ALL_TRANSACTIONS_FAILED"),
    GET_TRANSACTION_BY_ID_FAILED("GET_TRANSACTION_BY_ID_FAILED"),
    GET_TRANSACTION_BY_HASH_FAILED("GET_TRANSACTION_BY_HASH_FAILED"),
    GET_TRANSACTIONS_BY_ADDRESS_FAILED("GET_TRANSACTIONS_BY_ADDRESS_FAILED"),
    GET_PENDING_TRANSACTIONS_FAILED("GET_PENDING_TRANSACTIONS_FAILED"),
    
    // Blockchain related errors
    BLOCK_NOT_FOUND("BLOCK_NOT_FOUND"),
    MINING_FAILED("MINING_FAILED"),
    NO_PENDING_TRANSACTIONS("NO_PENDING_TRANSACTIONS"),
    BLOCKCHAIN_VALIDATION_FAILED("BLOCKCHAIN_VALIDATION_FAILED"),
    BLOCK_CREATION_FAILED("BLOCK_CREATION_FAILED"),
    STATS_CALCULATION_FAILED("STATS_CALCULATION_FAILED"),
    GET_ALL_BLOCKS_FAILED("GET_ALL_BLOCKS_FAILED"),
    GET_BLOCK_BY_ID_FAILED("GET_BLOCK_BY_ID_FAILED"),
    GET_BLOCK_BY_HASH_FAILED("GET_BLOCK_BY_HASH_FAILED"),
    GET_LATEST_BLOCK_FAILED("GET_LATEST_BLOCK_FAILED");
    
    private final String code;
    
    ErrorCode(String code) {
        this.code = code;
    }
    
    public String getCode() {
        return code;
    }
    
    @Override
    public String toString() {
        return code;
    }
}
